export { default as Profile } from './Profile/Profile'
export { default as About } from './Profile/About'
export { default as Donate } from './Profile/Donate'
export { default as ChoirRank } from './Profile/ChoirRank'
export { default as ManageAlarms } from './Profile/ManageAlarms'
